/*
SPDX-FileCopyrightText: 2026 M5Stack Technology CO LTD
SPDX-License-Identifier: MIT
*/

// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"stackChan/internal/dao/internal"
)

// agentDao is the data access object for the table agent.
type agentDao struct {
	*internal.AgentDao
}

var (
	// Agent is a globally accessible object for table agent operations.
	Agent = agentDao{internal.NewAgentDao()}
)

// Add your custom methods and functionality below.
