/*
SPDX-FileCopyrightText: 2026 M5Stack Technology CO LTD
SPDX-License-Identifier: MIT
*/

// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"stackChan/internal/dao/internal"
)

// chatMessageDao is the data access object for the table chat_message.
type chatMessageDao struct {
	*internal.ChatMessageDao
}

var (
	// ChatMessage is a globally accessible object for table chat_message operations.
	ChatMessage = chatMessageDao{internal.NewChatMessageDao()}
)

// Add your custom methods and functionality below.
